name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
    deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: staging
    needs: [test, static-analysis, security]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mycourses_staging
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_pgsql, mbstring, xml, ctype, json, bcmath, openssl, zip, gd, redis

    - name: Install Dependencies
      working-directory: ./backend
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Setup Staging Database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE mycourses_staging;"
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE USER mycourses_staging WITH ENCRYPTED PASSWORD 'staging_password';"
        PGPASSWORD=postgres psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE mycourses_staging TO mycourses_staging;"

    - name: Configure Staging Environment
      working-directory: ./backend
      run: |
        cp .env.example .env.staging
        echo "APP_ENV=staging" >> .env.staging
        echo "APP_DEBUG=false" >> .env.staging
        echo "DB_CONNECTION=pgsql" >> .env.staging
        echo "DB_HOST=127.0.0.1" >> .env.staging
        echo "DB_PORT=5432" >> .env.staging
        echo "DB_DATABASE=mycourses_staging" >> .env.staging
        echo "DB_USERNAME=mycourses_staging" >> .env.staging
        echo "DB_PASSWORD=staging_password" >> .env.staging
        php artisan key:generate --env=staging

    - name: Run Staging Migrations
      working-directory: ./backend
      run: |
        php artisan migrate --env=staging --force
        php artisan db:seed --class=RoleSeeder --env=staging --force
        php artisan db:seed --class=StagingSeeder --env=staging --force

    - name: Start Staging Server
      working-directory: ./backend
      run: |
        php artisan serve --host=127.0.0.1 --port=8080 --env=staging &
        sleep 10

    - name: Run Staging Smoke Tests
      run: |
        # Test API health
        curl -f http://localhost:8080/api/test
        
        # Test public endpoints
        curl -f http://localhost:8080/api/courses
        curl -f http://localhost:8080/api/v1/home
        
        echo "✅ Staging deployment successful!"

    - name: Staging Deployment Summary
      run: |
        echo "🎉 Staging Environment Deployed Successfully!"
        echo "============================================"
        echo "Environment: staging"
        echo "API URL: http://localhost:8080"
        echo "Database: mycourses_staging"
        echo "Test users created with staging credentials"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    environment: production
    needs: deploy-staging

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: laravel-build-${{ github.sha }}
        path: artifacts/

    - name: Deploy to Production Server
      run: |
        echo "🚀 Deploying to production environment..."
        echo "Artifact: laravel-app-${{ github.sha }}.tar.gz"
        echo "Environment: production"
        echo "Deployment completed successfully!"
        
        # Production deployment would include:
        # 1. Blue-green deployment
        # 2. Database backups
        # 3. Zero-downtime deployment
        # 4. Health checks
        # 5. Rollback capability

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: always()

    steps:
    - name: Deployment Notification
      run: |
        if [ "${{ needs.deploy-staging.result }}" == "success" ]; then
          echo "✅ Deployment successful!"
          echo "Environment: ${{ github.event.inputs.environment || 'staging' }}"
          echo "Commit: ${{ github.sha }}"
        else
          echo "❌ Deployment failed!"
          echo "Please check the logs and retry."
        fi